name: AWS Cdk
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Run CDK
        run: |
          cdk diff
          cdk deploy --require-approval=never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}